# application.properties — 환경 무관하게 공통으로 적용될 것만
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.web.pageable.default-page-size=10

spring.mvc.problemdetails.enabled=true
